set(CHIP_SERIESXX STM32F429xx)

include(${CMAKE_CURRENT_LIST_DIR}/../stm32f42xxx.cmake)

list(APPEND TARGET_COMPILE_DEFINITIONS
    -D${CHIP_SERIESXX}
)

list(APPEND TARGET_INCLUDE_DIRECTORIES 
    ${CMAKE_CURRENT_LIST_DIR}/inc
)

list(APPEND TARGET_SOURCE_FILES

)
