set(CHIP_SERIESXXX STM32F42xxx)



list(APPEND TARGET_COMPILE_DEFINITIONS
    -D${CHIP_SERIESXXX}
)

include(${CMAKE_CURRENT_LIST_DIR}/../stm32f4xx.cmake)

list(APPEND TARGET_INCLUDE_DIRECTORIES 
    ${CMAKE_CURRENT_LIST_DIR}/inc
)

list(APPEND TARGET_SOURCE_FILES

)