set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TOOLCHAIN_PREFIX "arm-none-eabi-")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER_FORCED TRUE)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(MCU cortex-m4)
set(FPU fpv4-sp-d16)
set(TARGET_COMPILE_DEFENITIONS ${TARGET_COMPILE_DEFENITIONS} -DSTM32F429xx)

set(TARGET_SOURCE_FILES ${TARGET_SOURCE_FILES} 
    ${CMAKE_CURRENT_LIST_DIR}/startup.S 
    ${CMAKE_CURRENT_LIST_DIR}/syscalls.c 
    ${CMAKE_CURRENT_LIST_DIR}/sysmem.c
    ${CMAKE_CURRENT_LIST_DIR}/src/system_stm32f4xx.c
)

set(TARGET_INCLUDE_DIRECTORIES ${TARGET_INCLUDE_DIRECTORIES} 
    ${CMAKE_CURRENT_LIST_DIR}/inc
)

set(TARGET_COMPILE_OPTIONS ${TARGET_COMPILE_OPTIONS}
    -mcpu=${MCU} 
    -mfpu=${FPU}
    -mfloat-abi=hard
    -mthumb
)

set(TARGET_LINK_OPTIONS ${TARGET_LINK_OPTIONS}
    -mcpu=${MCU} 
    -mfpu=${FPU}
    -mfloat-abi=hard
    -mthumb
    -T${CMAKE_SOURCE_DIR}/board/NUCLEO-f429zi/STM32F429ZITx_FLASH.ld
)